<?php
/*
Copyright 2012 Carlton Whitehead

This file is part of Autocross Instant Results.

Autocross Instant Results is free software: you can redistribute it and/or
modify it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Autocross Instant Results is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with Autocross Instant Results.  If not, see 
<http://www.gnu.org/licenses/>.
 */

$eventLabelModel = array(
    'event' => $this->event
);
echo $this->partial('events/event-label.phtml', $eventLabelModel);
?>
<h2>25 Newest Runs</h2>
<table class="results" id="newest-results">
    <thead>
        <tr>
            <th>Timestamp / Numbers</th>
            <th>Driver / Car</th>
            <th>Raw Time</th>
            <th>Pax Time</th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($this->runs as $run):
        $driver = $run->driver;
        ?>
        <tr>
            <td>
                <?= $run->getTimeOfDay() ?><br />
                <?php
                $driverHref = $this->baseUrl(
                    '/events/driver/event-id/' . $this->event->id .
                    '/driver-id/' . $driver->id
                );
                ?>
                <a href="<?= $driverHref ?>">
                    <?= $this->escape($driver->category->prefix.$driver->class->name.' '.$driver->number) ?>
                </a>
            </td>
            <td>
                    <?= $this->escape($driver->name) ?><br />
                    <?= $this->escape($driver->car) ?>
            </td>
            <?php
            echo $this->partial('events/run-time-cell.phtml', array(
                'run'=>$run
            ));
            ?>
            <td>
                <?= $run->timePaxWithPenalty ?>
            </td>
        </tr>
        <?php
    endforeach;
    if (count($this->runs) === 0):
        ?>
        <tr>
            <td>No runs (yet?)</td>
            <td colspan="2"></td>
        </tr>
        <?php
    endif;
    ?>
    </tbody>
</table>
