<?php
/*
Copyright 2012 Carlton Whitehead

This file is part of Autocross Instant Results.

Autocross Instant Results is free software: you can redistribute it and/or
modify it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Autocross Instant Results is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with Autocross Instant Results.  If not, see 
<http://www.gnu.org/licenses/>.
 */

?>
<td>
<?php
$run = $this->run;
$timeType = $this->timeType;
$withoutPenaltyField = 'time' . $timeType . 'Formatted';
$withPenaltyField = 'time' . $timeType . 'WithPenaltyFormatted';
if ($run->hasPenalty()):
    if ($run->isDnf()):
        if ($this->dnfTimeVisible):
            echo $this->escape($run->$withoutPenaltyField) . ' (DNF)';
        else:
            echo 'DNF';
        endif;
    else:
        if ($this->coneTimeVisible):
            echo $this->escape($run->$withoutPenaltyField) . ' + ' .
                $this->escape($run->penalty) .
                ' (' . $this->escape($run->$withPenaltyField) . ')';
        else:
            echo $this->escape($run->$withoutPenaltyField);
        endif;
        
    endif;
else:
    echo $this->escape($run->$withoutPenaltyField);
endif;
?>
</td>