<?php
/*
Copyright 2012 Carlton Whitehead

This file is part of Autocross Instant Results.

Autocross Instant Results is free software: you can redistribute it and/or
modify it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Autocross Instant Results is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with Autocross Instant Results.  If not, see 
<http://www.gnu.org/licenses/>.
 */
echo $this->doctype('HTML5');
?>
<html>
    <head>
        <?php
        $this->headMeta()->appendName(
                'viewport',
                'width=device-width, initial-scale=1, maximum-scale=1'
        );
        echo $this->headMeta();
        
        $hl = $this->headLink();
        $hl->appendStylesheet($this->baseUrl('/inuit.css/css/inuit.css'))
                ->appendStylesheet($this->baseUrl('/inuit.css/css/grid.inuit.css'))
                ->appendStylesheet($this->baseUrl('/inuit.css/css/keywords.inuit.css'))
                ->appendStylesheet($this->baseUrl('/style.css'));
                
        echo $this->headLink();
        
        $this->headScript()
                ->prependFile($this->baseUrl('/js/jquery-1.6.4.min.js'));
        echo $this->headScript();
        ?>
        
    </head>
    <body class="wrapper" id="top">
        <?php
        echo $this->navigation()->breadcrumbs()->setSeparator(' &#9654; ');
        echo $this->layout()->content;
        echo $this->partial('footer.phtml');
        ?>
    </body>
</html>
<?php

